### ISSUE TITLE
Does CSR8510 work after waking from sleep?

### ISSUE THREAD

**Issue by mrdc** [d3fa/MACOS-EFI-Gigabyte-Z370-QTJ1-UHD630#1]
Hello,

Does your CSR8510 works after waking from Sleep in Ventura?
I have an issue: CSR8510 stop working after wake up and unplugging/plugging doesn't help. Only restart.

Thanks

**Comment by d3fa** [comment]
Hey
I dont use sleep mode and macos its just for fun :)
But i'm tested and i have same issue with bluetooth in mac os Sonoma.
I updated some kexts and You can try to download them.
For proper BT works seems to be need only 3 kext
- BlueToolFixup.kext
- BrcmFirmwareData.kext
- IntelBTPatcher.kext

i have other issue with sleep! After waking macos works weird: BT works :) but all other programs is laggy and frozen. Only reboot... i deleted all 'BT kext', eject Usb dongle and problem was not resolv

**Comment by mrdc** [comment]
> but all other programs is laggy and frozen. Only reboot... i deleted all 'BT kext', eject Usb dongle and problem was not resolv


I've read somewhere, that IntelBTPatcher can cause issues.
Maybe cpu power management is not activated after sleep? Try checking IOReg CPU PM management and check if Powerstates are populated with value. 
Are there any process which has high CPU? Coreduet? kernel_task?

**Comment by mrdc** [comment]
> After waking macos works weird: BT works :)

Does it connect to any device? For me the BT icon is shown, but BT doesn't connect to any device.
I've added these kexts as you suggested: 
```
BrcmFirmwareData.kext
IntelBTPatcher.kext
```

**Comment by d3fa** [comment]
sorry i forgot to reply quicly
Yes is working and connect to devices.

But my macos Sonoma still doesn't work properly after sleep and eventually i guess the reason is Bluetooth

**Comment by d3fa** [comment]
https://www.tonymacx86.com/threads/10-9-bluetooth-csr8510-a10-not-recognised-as-bluetooth.116502/

mb this help

**Comment by mrdc** [comment]
> https://www.tonymacx86.com/threads/10-9-bluetooth-csr8510-a10-not-recognised-as-bluetooth.116502/
> 
> mb this help

Thanks, I've fixed it already by using USB Hub - works well after sleep.
